/**
 * SQLite store implementations for all 10 cross-cutting components.
 * Auto-generated by scripts/generate_vertical_stores.py.
 *
 * Each class implements the corresponding component's Store interface,
 * backed by a SQLite table. All data is tenant-scoped.
 */

import type { DatabaseType } from "../../database";
import type { EntityId, TenantId } from "@business-os/shared";

import type { TimelineEvent, ActivityTimelineStore } from "@business-os/components/cross-cutting/activity-timeline/backend";
import type { Document, DocumentManagementStore } from "@business-os/components/cross-cutting/document-management/backend";
import type { FormDefinition, FormSubmission, FormsAndIntakeStore } from "@business-os/components/cross-cutting/forms-and-intake/backend";
import type { Message, MessagingCenterStore } from "@business-os/components/cross-cutting/messaging-center/backend";
import type { Note, NotesAndCommentsStore } from "@business-os/components/cross-cutting/notes-and-comments/backend";
import type { Notification, NotificationsCenterStore } from "@business-os/components/cross-cutting/notifications-center/backend";
import type { Payment, PaymentsOrCollectionsStore } from "@business-os/components/cross-cutting/payments-or-collections/backend";
import type { Metric, MetricValue, ReportingDashboardStore } from "@business-os/components/cross-cutting/reporting-dashboard/backend";
import type { RoleDefinition, RolesAndPermissionsUiStore } from "@business-os/components/cross-cutting/roles-and-permissions-ui/backend";
import type { SavedQuery, SearchAndFilterStore } from "@business-os/components/cross-cutting/search-and-filter/backend";

// ============================================================
// Helper: generic CRUD factory
// ============================================================
function makeCrud<T>(db: DatabaseType, config: {
  table: string;
  columns: readonly string[];
  fromRow: (row: Record<string, unknown>) => T;
  toParams: (tenantId: string, entity: T) => Record<string, unknown>;
}) {
  const { table, columns, fromRow, toParams } = config;
  const colList = columns.join(", ");
  const paramList = columns.map((c) => `@${c}`).join(", ");
  const updateList = columns
    .filter((c) => c !== "id" && c !== "created_at")
    .map((c) => `${c} = @${c}`)
    .join(", ");
  return {
    get(tenantId: string, id: EntityId): T | undefined {
      const row = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ? AND id = ?`).get(tenantId, id) as Record<string, unknown> | undefined;
      return row ? fromRow(row) : undefined;
    },
    put(tenantId: string, entity: T): void {
      const params = toParams(tenantId, entity);
      db.prepare(`INSERT INTO ${table} (${colList}) VALUES (${paramList}) ON CONFLICT(id) DO UPDATE SET ${updateList}`).run(params);
    },
    list(tenantId: string): readonly T[] {
      const rows = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ?`).all(tenantId) as Record<string, unknown>[];
      return rows.map(fromRow);
    },
    delete(tenantId: string, id: EntityId): boolean {
      const result = db.prepare(`DELETE FROM ${table} WHERE tenant_id = ? AND id = ?`).run(tenantId, id);
      return result.changes > 0;
    },
  };
}

// ============================================================
// activity-timeline
// ============================================================
const Timeline_eventCrud = (db: DatabaseType) => makeCrud<TimelineEvent>(db, {
  table: "activity_timeline_events",
  columns: ["id", "tenant_id", "entity_type", "entity_id", "action", "summary", "actor_user_id", "occurred_at", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    entityType: r.entity_type as string,
    entityId: r.entity_id as string,
    action: r.action as string,
    summary: r.summary as string,
    actorUserId: r.actor_user_id as string,
    occurredAt: r.occurred_at as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    entity_type: e.entityType,
    entity_id: e.entityId,
    action: e.action,
    summary: e.summary,
    actor_user_id: e.actorUserId,
    occurred_at: e.occurredAt,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteActivityTimelineStore implements ActivityTimelineStore {
  constructor(private readonly db: DatabaseType) {}
  getTimelineEvent(t: string, id: EntityId) { return Timeline_eventCrud(this.db).get(t, id); }
  putTimelineEvent(t: string, e: TimelineEvent) { Timeline_eventCrud(this.db).put(t, e); }
  listTimelineEvents(t: string) { return Timeline_eventCrud(this.db).list(t); }
  deleteTimelineEvent(t: string, id: EntityId) { return Timeline_eventCrud(this.db).delete(t, id); }
}

// ============================================================
// document-management
// ============================================================
const DocumentCrud = (db: DatabaseType) => makeCrud<Document>(db, {
  table: "document_documents",
  columns: ["id", "tenant_id", "file_name", "mime_type", "size_bytes", "storage_key", "entity_type", "entity_id", "kind", "deleted_at", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    fileName: r.file_name as string,
    mimeType: r.mime_type as string,
    sizeBytes: r.size_bytes as number,
    storageKey: r.storage_key as string,
    entityType: r.entity_type as string,
    entityId: r.entity_id as string,
    kind: r.kind as string,
    deletedAt: (r.deleted_at as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    file_name: e.fileName,
    mime_type: e.mimeType,
    size_bytes: e.sizeBytes,
    storage_key: e.storageKey,
    entity_type: e.entityType,
    entity_id: e.entityId,
    kind: e.kind,
    deleted_at: e.deletedAt,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteDocumentManagementStore implements DocumentManagementStore {
  constructor(private readonly db: DatabaseType) {}
  getDocument(t: string, id: EntityId) { return DocumentCrud(this.db).get(t, id); }
  putDocument(t: string, e: Document) { DocumentCrud(this.db).put(t, e); }
  listDocuments(t: string) { return DocumentCrud(this.db).list(t); }
  deleteDocument(t: string, id: EntityId) { return DocumentCrud(this.db).delete(t, id); }
}

// ============================================================
// forms-and-intake
// ============================================================
const Form_definitionCrud = (db: DatabaseType) => makeCrud<FormDefinition>(db, {
  table: "forms_form_definitions",
  columns: ["id", "tenant_id", "slug", "title", "description", "fields_json", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    slug: r.slug as string,
    title: r.title as string,
    description: (r.description as string | null) ?? null,
    fieldsJson: r.fields_json as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    slug: e.slug,
    title: e.title,
    description: e.description,
    fields_json: e.fieldsJson,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const Form_submissionCrud = (db: DatabaseType) => makeCrud<FormSubmission>(db, {
  table: "forms_form_submissions",
  columns: ["id", "tenant_id", "form_id", "values_json", "submitted_by_user_id", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    formId: r.form_id as string,
    valuesJson: r.values_json as string,
    submittedByUserId: (r.submitted_by_user_id as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    form_id: e.formId,
    values_json: e.valuesJson,
    submitted_by_user_id: e.submittedByUserId,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteFormsAndIntakeStore implements FormsAndIntakeStore {
  constructor(private readonly db: DatabaseType) {}
  getFormDefinition(t: string, id: EntityId) { return Form_definitionCrud(this.db).get(t, id); }
  putFormDefinition(t: string, e: FormDefinition) { Form_definitionCrud(this.db).put(t, e); }
  listFormDefinitions(t: string) { return Form_definitionCrud(this.db).list(t); }
  deleteFormDefinition(t: string, id: EntityId) { return Form_definitionCrud(this.db).delete(t, id); }
  getFormSubmission(t: string, id: EntityId) { return Form_submissionCrud(this.db).get(t, id); }
  putFormSubmission(t: string, e: FormSubmission) { Form_submissionCrud(this.db).put(t, e); }
  listFormSubmissions(t: string) { return Form_submissionCrud(this.db).list(t); }
  deleteFormSubmission(t: string, id: EntityId) { return Form_submissionCrud(this.db).delete(t, id); }
}

// ============================================================
// messaging-center
// ============================================================
const MessageCrud = (db: DatabaseType) => makeCrud<Message>(db, {
  table: "messaging_messages",
  columns: ["id", "tenant_id", "recipient_id", "channel", "template_key", "variables", "status", "sent_at", "delivered_at", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    recipientId: r.recipient_id as string,
    channel: r.channel as string,
    templateKey: r.template_key as string,
    variables: r.variables ? JSON.parse(r.variables as string) as Record<string, string> : null,
    status: r.status as string,
    sentAt: (r.sent_at as string | null) ?? null,
    deliveredAt: (r.delivered_at as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    recipient_id: e.recipientId,
    channel: e.channel,
    template_key: e.templateKey,
    variables: e.variables ? JSON.stringify(e.variables) : null,
    status: e.status,
    sent_at: e.sentAt,
    delivered_at: e.deliveredAt,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteMessagingCenterStore implements MessagingCenterStore {
  constructor(private readonly db: DatabaseType) {}
  getMessage(t: string, id: EntityId) { return MessageCrud(this.db).get(t, id); }
  putMessage(t: string, e: Message) { MessageCrud(this.db).put(t, e); }
  listMessages(t: string) { return MessageCrud(this.db).list(t); }
  deleteMessage(t: string, id: EntityId) { return MessageCrud(this.db).delete(t, id); }
}

// ============================================================
// notes-and-comments
// ============================================================
const NoteCrud = (db: DatabaseType) => makeCrud<Note>(db, {
  table: "notes_notes",
  columns: ["id", "tenant_id", "body", "entity_type", "entity_id", "parent_id", "visibility", "edited_at", "deleted_at", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    body: r.body as string,
    entityType: r.entity_type as string,
    entityId: r.entity_id as string,
    parentId: (r.parent_id as string | null) ?? null,
    visibility: r.visibility as string,
    editedAt: (r.edited_at as string | null) ?? null,
    deletedAt: (r.deleted_at as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    body: e.body,
    entity_type: e.entityType,
    entity_id: e.entityId,
    parent_id: e.parentId,
    visibility: e.visibility,
    edited_at: e.editedAt,
    deleted_at: e.deletedAt,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteNotesAndCommentsStore implements NotesAndCommentsStore {
  constructor(private readonly db: DatabaseType) {}
  getNote(t: string, id: EntityId) { return NoteCrud(this.db).get(t, id); }
  putNote(t: string, e: Note) { NoteCrud(this.db).put(t, e); }
  listNotes(t: string) { return NoteCrud(this.db).list(t); }
  deleteNote(t: string, id: EntityId) { return NoteCrud(this.db).delete(t, id); }
}

// ============================================================
// notifications-center
// ============================================================
const NotificationCrud = (db: DatabaseType) => makeCrud<Notification>(db, {
  table: "notifications_notifications",
  columns: ["id", "tenant_id", "recipient_user_id", "title", "body", "action_label", "action_url", "read_at", "dismissed_at", "expires_at", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    recipientUserId: r.recipient_user_id as string,
    title: r.title as string,
    body: r.body as string,
    actionLabel: (r.action_label as string | null) ?? null,
    actionUrl: (r.action_url as string | null) ?? null,
    readAt: (r.read_at as string | null) ?? null,
    dismissedAt: (r.dismissed_at as string | null) ?? null,
    expiresAt: r.expires_at as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    recipient_user_id: e.recipientUserId,
    title: e.title,
    body: e.body,
    action_label: e.actionLabel,
    action_url: e.actionUrl,
    read_at: e.readAt,
    dismissed_at: e.dismissedAt,
    expires_at: e.expiresAt,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteNotificationsCenterStore implements NotificationsCenterStore {
  constructor(private readonly db: DatabaseType) {}
  getNotification(t: string, id: EntityId) { return NotificationCrud(this.db).get(t, id); }
  putNotification(t: string, e: Notification) { NotificationCrud(this.db).put(t, e); }
  listNotifications(t: string) { return NotificationCrud(this.db).list(t); }
  deleteNotification(t: string, id: EntityId) { return NotificationCrud(this.db).delete(t, id); }
}

// ============================================================
// payments-or-collections
// ============================================================
const PaymentCrud = (db: DatabaseType) => makeCrud<Payment>(db, {
  table: "payments_payments",
  columns: ["id", "tenant_id", "amount", "currency", "method", "provider_reference", "invoice_id", "payer_name", "status", "refunded_at", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    amount: r.amount as number,
    currency: r.currency as string,
    method: r.method as string,
    providerReference: (r.provider_reference as string | null) ?? null,
    invoiceId: (r.invoice_id as string | null) ?? null,
    payerName: (r.payer_name as string | null) ?? null,
    status: r.status as string,
    refundedAt: (r.refunded_at as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    amount: e.amount,
    currency: e.currency,
    method: e.method,
    provider_reference: e.providerReference,
    invoice_id: e.invoiceId,
    payer_name: e.payerName,
    status: e.status,
    refunded_at: e.refundedAt,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqlitePaymentsOrCollectionsStore implements PaymentsOrCollectionsStore {
  constructor(private readonly db: DatabaseType) {}
  getPayment(t: string, id: EntityId) { return PaymentCrud(this.db).get(t, id); }
  putPayment(t: string, e: Payment) { PaymentCrud(this.db).put(t, e); }
  listPayments(t: string) { return PaymentCrud(this.db).list(t); }
  deletePayment(t: string, id: EntityId) { return PaymentCrud(this.db).delete(t, id); }
}

// ============================================================
// reporting-dashboard
// ============================================================
const MetricCrud = (db: DatabaseType) => makeCrud<Metric>(db, {
  table: "reporting_metrics",
  columns: ["id", "tenant_id", "key", "name", "source_query", "refresh_interval_seconds", "owner_user_id", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    key: r.key as string,
    name: r.name as string,
    sourceQuery: r.source_query as string,
    refreshIntervalSeconds: r.refresh_interval_seconds as number,
    ownerUserId: r.owner_user_id as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    key: e.key,
    name: e.name,
    source_query: e.sourceQuery,
    refresh_interval_seconds: e.refreshIntervalSeconds,
    owner_user_id: e.ownerUserId,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const Metric_valueCrud = (db: DatabaseType) => makeCrud<MetricValue>(db, {
  table: "reporting_metric_values",
  columns: ["id", "tenant_id", "metric_key", "computed_at", "window_start", "window_end", "value", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    metricKey: r.metric_key as string,
    computedAt: r.computed_at as string,
    windowStart: r.window_start as string,
    windowEnd: r.window_end as string,
    value: r.value as number,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    metric_key: e.metricKey,
    computed_at: e.computedAt,
    window_start: e.windowStart,
    window_end: e.windowEnd,
    value: e.value,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteReportingDashboardStore implements ReportingDashboardStore {
  constructor(private readonly db: DatabaseType) {}
  getMetric(t: string, id: EntityId) { return MetricCrud(this.db).get(t, id); }
  putMetric(t: string, e: Metric) { MetricCrud(this.db).put(t, e); }
  listMetrics(t: string) { return MetricCrud(this.db).list(t); }
  deleteMetric(t: string, id: EntityId) { return MetricCrud(this.db).delete(t, id); }
  getMetricValue(t: string, id: EntityId) { return Metric_valueCrud(this.db).get(t, id); }
  putMetricValue(t: string, e: MetricValue) { Metric_valueCrud(this.db).put(t, e); }
  listMetricValues(t: string) { return Metric_valueCrud(this.db).list(t); }
  deleteMetricValue(t: string, id: EntityId) { return Metric_valueCrud(this.db).delete(t, id); }
}

// ============================================================
// roles-and-permissions-ui
// ============================================================
const Role_definitionCrud = (db: DatabaseType) => makeCrud<RoleDefinition>(db, {
  table: "roles_role_definitions",
  columns: ["id", "tenant_id", "name", "description", "permissions_json", "is_system", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    description: (r.description as string | null) ?? null,
    permissionsJson: r.permissions_json as string,
    isSystem: r.is_system === 1,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    description: e.description,
    permissions_json: e.permissionsJson,
    is_system: e.isSystem ? 1 : 0,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteRolesAndPermissionsUiStore implements RolesAndPermissionsUiStore {
  constructor(private readonly db: DatabaseType) {}
  getRoleDefinition(t: string, id: EntityId) { return Role_definitionCrud(this.db).get(t, id); }
  putRoleDefinition(t: string, e: RoleDefinition) { Role_definitionCrud(this.db).put(t, e); }
  listRoleDefinitions(t: string) { return Role_definitionCrud(this.db).list(t); }
  deleteRoleDefinition(t: string, id: EntityId) { return Role_definitionCrud(this.db).delete(t, id); }
}

// ============================================================
// search-and-filter
// ============================================================
const Saved_queryCrud = (db: DatabaseType) => makeCrud<SavedQuery>(db, {
  table: "search_saved_queries",
  columns: ["id", "tenant_id", "name", "entity_type", "query_text", "filters_json", "sort_field", "sort_direction", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    entityType: r.entity_type as string,
    queryText: (r.query_text as string | null) ?? null,
    filtersJson: (r.filters_json as string | null) ?? null,
    sortField: (r.sort_field as string | null) ?? null,
    sortDirection: r.sort_direction as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    entity_type: e.entityType,
    query_text: e.queryText,
    filters_json: e.filtersJson,
    sort_field: e.sortField,
    sort_direction: e.sortDirection,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteSearchAndFilterStore implements SearchAndFilterStore {
  constructor(private readonly db: DatabaseType) {}
  getSavedQuery(t: string, id: EntityId) { return Saved_queryCrud(this.db).get(t, id); }
  putSavedQuery(t: string, e: SavedQuery) { Saved_queryCrud(this.db).put(t, e); }
  listSavedQuerys(t: string) { return Saved_queryCrud(this.db).list(t); }
  deleteSavedQuery(t: string, id: EntityId) { return Saved_queryCrud(this.db).delete(t, id); }
}
