/**
 * SQLite store implementations for all 8 churches components.
 * Auto-generated by scripts/generate_vertical_stores.py.
 *
 * Each class implements the corresponding component's Store interface,
 * backed by a SQLite table. All data is tenant-scoped.
 */

import type { DatabaseType } from "../../database";
import type { EntityId, TenantId } from "@business-os/shared";

import type { Announcement, ChurchAnnouncementsStore } from "@business-os/components/churches/church-announcements/backend";
import type { ServiceAttendance, ChurchAttendanceStore } from "@business-os/components/churches/church-attendance/backend";
import type { Donation, Pledge, ChurchDonationsStore } from "@business-os/components/churches/church-donations/backend";
import type { Event, EventRegistration, ChurchEventsStore } from "@business-os/components/churches/church-events/backend";
import type { Group, GroupMembership, ChurchGroupsStore } from "@business-os/components/churches/church-groups/backend";
import type { Member, ChurchMemberManagementStore } from "@business-os/components/churches/church-member-management/backend";
import type { Sermon, ChurchSermonsStore } from "@business-os/components/churches/church-sermons/backend";
import type { Volunteer, VolunteerAssignment, ChurchVolunteersStore } from "@business-os/components/churches/church-volunteers/backend";

// ============================================================
// Helper: generic CRUD factory
// ============================================================
function makeCrud<T>(db: DatabaseType, config: {
  table: string;
  columns: readonly string[];
  fromRow: (row: Record<string, unknown>) => T;
  toParams: (tenantId: string, entity: T) => Record<string, unknown>;
}) {
  const { table, columns, fromRow, toParams } = config;
  const colList = columns.join(", ");
  const paramList = columns.map((c) => `@${c}`).join(", ");
  const updateList = columns
    .filter((c) => c !== "id" && c !== "created_at")
    .map((c) => `${c} = @${c}`)
    .join(", ");
  return {
    get(tenantId: string, id: EntityId): T | undefined {
      const row = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ? AND id = ?`).get(tenantId, id) as Record<string, unknown> | undefined;
      return row ? fromRow(row) : undefined;
    },
    put(tenantId: string, entity: T): void {
      const params = toParams(tenantId, entity);
      db.prepare(`INSERT INTO ${table} (${colList}) VALUES (${paramList}) ON CONFLICT(id) DO UPDATE SET ${updateList}`).run(params);
    },
    list(tenantId: string): readonly T[] {
      const rows = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ?`).all(tenantId) as Record<string, unknown>[];
      return rows.map(fromRow);
    },
    delete(tenantId: string, id: EntityId): boolean {
      const result = db.prepare(`DELETE FROM ${table} WHERE tenant_id = ? AND id = ?`).run(tenantId, id);
      return result.changes > 0;
    },
  };
}

// ============================================================
// church-announcements
// ============================================================
const AnnouncementCrud = (db: DatabaseType) => makeCrud<Announcement>(db, {
  table: "church_announcements",
  columns: ["id", "tenant_id", "title", "body", "audience", "expires_at", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    title: r.title as string,
    body: r.body as string,
    audience: r.audience as string,
    expiresAt: r.expires_at as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    title: e.title,
    body: e.body,
    audience: e.audience,
    expires_at: e.expiresAt,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteChurchAnnouncementsStore implements ChurchAnnouncementsStore {
  constructor(private readonly db: DatabaseType) {}
  getAnnouncement(t: string, id: EntityId) { return AnnouncementCrud(this.db).get(t, id); }
  putAnnouncement(t: string, e: Announcement) { AnnouncementCrud(this.db).put(t, e); }
  listAnnouncements(t: string) { return AnnouncementCrud(this.db).list(t); }
  deleteAnnouncement(t: string, id: EntityId) { return AnnouncementCrud(this.db).delete(t, id); }
}

// ============================================================
// church-attendance
// ============================================================
const Service_attendanceCrud = (db: DatabaseType) => makeCrud<ServiceAttendance>(db, {
  table: "church_service_attendances",
  columns: ["id", "tenant_id", "member_id", "service_date", "attended", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    memberId: r.member_id as string,
    serviceDate: r.service_date as string,
    attended: r.attended === 1,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    member_id: e.memberId,
    service_date: e.serviceDate,
    attended: e.attended ? 1 : 0,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteChurchAttendanceStore implements ChurchAttendanceStore {
  constructor(private readonly db: DatabaseType) {}
  getServiceAttendance(t: string, id: EntityId) { return Service_attendanceCrud(this.db).get(t, id); }
  putServiceAttendance(t: string, e: ServiceAttendance) { Service_attendanceCrud(this.db).put(t, e); }
  listServiceAttendances(t: string) { return Service_attendanceCrud(this.db).list(t); }
  deleteServiceAttendance(t: string, id: EntityId) { return Service_attendanceCrud(this.db).delete(t, id); }
}

// ============================================================
// church-donations
// ============================================================
const DonationCrud = (db: DatabaseType) => makeCrud<Donation>(db, {
  table: "church_donations",
  columns: ["id", "tenant_id", "member_id", "amount_cents", "currency", "fund", "method", "payment_reference", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    memberId: r.member_id as string,
    amountCents: r.amount_cents as number,
    currency: r.currency as string,
    fund: r.fund as string,
    method: r.method as string,
    paymentReference: (r.payment_reference as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    member_id: e.memberId,
    amount_cents: e.amountCents,
    currency: e.currency,
    fund: e.fund,
    method: e.method,
    payment_reference: e.paymentReference,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const PledgeCrud = (db: DatabaseType) => makeCrud<Pledge>(db, {
  table: "church_pledges",
  columns: ["id", "tenant_id", "member_id", "target_amount_cents", "currency", "fund", "due_date", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    memberId: r.member_id as string,
    targetAmountCents: r.target_amount_cents as number,
    currency: r.currency as string,
    fund: r.fund as string,
    dueDate: r.due_date as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    member_id: e.memberId,
    target_amount_cents: e.targetAmountCents,
    currency: e.currency,
    fund: e.fund,
    due_date: e.dueDate,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteChurchDonationsStore implements ChurchDonationsStore {
  constructor(private readonly db: DatabaseType) {}
  getDonation(t: string, id: EntityId) { return DonationCrud(this.db).get(t, id); }
  putDonation(t: string, e: Donation) { DonationCrud(this.db).put(t, e); }
  listDonations(t: string) { return DonationCrud(this.db).list(t); }
  deleteDonation(t: string, id: EntityId) { return DonationCrud(this.db).delete(t, id); }
  getPledge(t: string, id: EntityId) { return PledgeCrud(this.db).get(t, id); }
  putPledge(t: string, e: Pledge) { PledgeCrud(this.db).put(t, e); }
  listPledges(t: string) { return PledgeCrud(this.db).list(t); }
  deletePledge(t: string, id: EntityId) { return PledgeCrud(this.db).delete(t, id); }
}

// ============================================================
// church-events
// ============================================================
const EventCrud = (db: DatabaseType) => makeCrud<Event>(db, {
  table: "church_events",
  columns: ["id", "tenant_id", "name", "description", "starts_at", "ends_at", "location", "capacity", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    description: (r.description as string | null) ?? null,
    startsAt: r.starts_at as string,
    endsAt: r.ends_at as string,
    location: (r.location as string | null) ?? null,
    capacity: r.capacity as number,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    description: e.description,
    starts_at: e.startsAt,
    ends_at: e.endsAt,
    location: e.location,
    capacity: e.capacity,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const Event_registrationCrud = (db: DatabaseType) => makeCrud<EventRegistration>(db, {
  table: "church_event_registrations",
  columns: ["id", "tenant_id", "event_id", "member_id", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    eventId: r.event_id as string,
    memberId: r.member_id as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    event_id: e.eventId,
    member_id: e.memberId,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteChurchEventsStore implements ChurchEventsStore {
  constructor(private readonly db: DatabaseType) {}
  getEvent(t: string, id: EntityId) { return EventCrud(this.db).get(t, id); }
  putEvent(t: string, e: Event) { EventCrud(this.db).put(t, e); }
  listEvents(t: string) { return EventCrud(this.db).list(t); }
  deleteEvent(t: string, id: EntityId) { return EventCrud(this.db).delete(t, id); }
  getEventRegistration(t: string, id: EntityId) { return Event_registrationCrud(this.db).get(t, id); }
  putEventRegistration(t: string, e: EventRegistration) { Event_registrationCrud(this.db).put(t, e); }
  listEventRegistrations(t: string) { return Event_registrationCrud(this.db).list(t); }
  deleteEventRegistration(t: string, id: EntityId) { return Event_registrationCrud(this.db).delete(t, id); }
}

// ============================================================
// church-groups
// ============================================================
const GroupCrud = (db: DatabaseType) => makeCrud<Group>(db, {
  table: "church_groups",
  columns: ["id", "tenant_id", "name", "description", "leader_member_id", "max_members", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    description: (r.description as string | null) ?? null,
    leaderMemberId: r.leader_member_id as string,
    maxMembers: r.max_members as number,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    description: e.description,
    leader_member_id: e.leaderMemberId,
    max_members: e.maxMembers,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const Group_membershipCrud = (db: DatabaseType) => makeCrud<GroupMembership>(db, {
  table: "church_group_memberships",
  columns: ["id", "tenant_id", "group_id", "member_id", "role", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    groupId: r.group_id as string,
    memberId: r.member_id as string,
    role: r.role as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    group_id: e.groupId,
    member_id: e.memberId,
    role: e.role,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteChurchGroupsStore implements ChurchGroupsStore {
  constructor(private readonly db: DatabaseType) {}
  getGroup(t: string, id: EntityId) { return GroupCrud(this.db).get(t, id); }
  putGroup(t: string, e: Group) { GroupCrud(this.db).put(t, e); }
  listGroups(t: string) { return GroupCrud(this.db).list(t); }
  deleteGroup(t: string, id: EntityId) { return GroupCrud(this.db).delete(t, id); }
  getGroupMembership(t: string, id: EntityId) { return Group_membershipCrud(this.db).get(t, id); }
  putGroupMembership(t: string, e: GroupMembership) { Group_membershipCrud(this.db).put(t, e); }
  listGroupMemberships(t: string) { return Group_membershipCrud(this.db).list(t); }
  deleteGroupMembership(t: string, id: EntityId) { return Group_membershipCrud(this.db).delete(t, id); }
}

// ============================================================
// church-member-management
// ============================================================
const MemberCrud = (db: DatabaseType) => makeCrud<Member>(db, {
  table: "church_members",
  columns: ["id", "tenant_id", "first_name", "last_name", "phone", "email", "family_id", "membership_status", "directory_visibility", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    firstName: r.first_name as string,
    lastName: r.last_name as string,
    phone: (r.phone as string | null) ?? null,
    email: (r.email as string | null) ?? null,
    familyId: (r.family_id as string | null) ?? null,
    membershipStatus: r.membership_status as string,
    directoryVisibility: r.directory_visibility as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    first_name: e.firstName,
    last_name: e.lastName,
    phone: e.phone,
    email: e.email,
    family_id: e.familyId,
    membership_status: e.membershipStatus,
    directory_visibility: e.directoryVisibility,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteChurchMemberManagementStore implements ChurchMemberManagementStore {
  constructor(private readonly db: DatabaseType) {}
  getMember(t: string, id: EntityId) { return MemberCrud(this.db).get(t, id); }
  putMember(t: string, e: Member) { MemberCrud(this.db).put(t, e); }
  listMembers(t: string) { return MemberCrud(this.db).list(t); }
  deleteMember(t: string, id: EntityId) { return MemberCrud(this.db).delete(t, id); }
}

// ============================================================
// church-sermons
// ============================================================
const SermonCrud = (db: DatabaseType) => makeCrud<Sermon>(db, {
  table: "church_sermons",
  columns: ["id", "tenant_id", "title", "speaker_member_id", "delivered_at", "scripture_references", "series_id", "audio_document_id", "video_document_id", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    title: r.title as string,
    speakerMemberId: r.speaker_member_id as string,
    deliveredAt: r.delivered_at as string,
    scriptureReferences: (r.scripture_references as string | null) ?? null,
    seriesId: (r.series_id as string | null) ?? null,
    audioDocumentId: (r.audio_document_id as string | null) ?? null,
    videoDocumentId: (r.video_document_id as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    title: e.title,
    speaker_member_id: e.speakerMemberId,
    delivered_at: e.deliveredAt,
    scripture_references: e.scriptureReferences,
    series_id: e.seriesId,
    audio_document_id: e.audioDocumentId,
    video_document_id: e.videoDocumentId,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteChurchSermonsStore implements ChurchSermonsStore {
  constructor(private readonly db: DatabaseType) {}
  getSermon(t: string, id: EntityId) { return SermonCrud(this.db).get(t, id); }
  putSermon(t: string, e: Sermon) { SermonCrud(this.db).put(t, e); }
  listSermons(t: string) { return SermonCrud(this.db).list(t); }
  deleteSermon(t: string, id: EntityId) { return SermonCrud(this.db).delete(t, id); }
}

// ============================================================
// church-volunteers
// ============================================================
const VolunteerCrud = (db: DatabaseType) => makeCrud<Volunteer>(db, {
  table: "church_volunteers",
  columns: ["id", "tenant_id", "member_id", "role", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    memberId: r.member_id as string,
    role: r.role as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    member_id: e.memberId,
    role: e.role,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const Volunteer_assignmentCrud = (db: DatabaseType) => makeCrud<VolunteerAssignment>(db, {
  table: "church_volunteer_assignments",
  columns: ["id", "tenant_id", "volunteer_id", "assignment_type", "assignment_id", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    volunteerId: r.volunteer_id as string,
    assignmentType: r.assignment_type as string,
    assignmentId: r.assignment_id as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    volunteer_id: e.volunteerId,
    assignment_type: e.assignmentType,
    assignment_id: e.assignmentId,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteChurchVolunteersStore implements ChurchVolunteersStore {
  constructor(private readonly db: DatabaseType) {}
  getVolunteer(t: string, id: EntityId) { return VolunteerCrud(this.db).get(t, id); }
  putVolunteer(t: string, e: Volunteer) { VolunteerCrud(this.db).put(t, e); }
  listVolunteers(t: string) { return VolunteerCrud(this.db).list(t); }
  deleteVolunteer(t: string, id: EntityId) { return VolunteerCrud(this.db).delete(t, id); }
  getVolunteerAssignment(t: string, id: EntityId) { return Volunteer_assignmentCrud(this.db).get(t, id); }
  putVolunteerAssignment(t: string, e: VolunteerAssignment) { Volunteer_assignmentCrud(this.db).put(t, e); }
  listVolunteerAssignments(t: string) { return Volunteer_assignmentCrud(this.db).list(t); }
  deleteVolunteerAssignment(t: string, id: EntityId) { return Volunteer_assignmentCrud(this.db).delete(t, id); }
}
