/**
 * SQLite store implementations for all 9 retail-shops components.
 * Auto-generated by scripts/generate_vertical_stores.py.
 *
 * Each class implements the corresponding component's Store interface,
 * backed by a SQLite table. All data is tenant-scoped.
 */

import type { DatabaseType } from "../../database";
import type { EntityId, TenantId } from "@business-os/shared";

import type { Barcode, RetailBarcodeScanningStore } from "@business-os/components/retail-shops/retail-barcode-scanning/backend";
import type { Customer, RetailCustomerManagementStore } from "@business-os/components/retail-shops/retail-customer-management/backend";
import type { StockLevel, StockMovement, RetailInventoryStore } from "@business-os/components/retail-shops/retail-inventory/backend";
import type { Sale, RetailPointOfSaleStore } from "@business-os/components/retail-shops/retail-point-of-sale/backend";
import type { Category, Product, RetailProductCatalogStore } from "@business-os/components/retail-shops/retail-product-catalog/backend";
import type { Promotion, RetailPromotionsStore } from "@business-os/components/retail-shops/retail-promotions/backend";
import type { SaleRecord, DailySalesSummary, RetailSalesReportsStore } from "@business-os/components/retail-shops/retail-sales-reports/backend";
import type { StockAlert, RetailStockAlertsStore } from "@business-os/components/retail-shops/retail-stock-alerts/backend";
import type { Supplier, PurchaseOrder, RetailSupplierManagementStore } from "@business-os/components/retail-shops/retail-supplier-management/backend";

// ============================================================
// Helper: generic CRUD factory
// ============================================================
function makeCrud<T>(db: DatabaseType, config: {
  table: string;
  columns: readonly string[];
  fromRow: (row: Record<string, unknown>) => T;
  toParams: (tenantId: string, entity: T) => Record<string, unknown>;
}) {
  const { table, columns, fromRow, toParams } = config;
  const colList = columns.join(", ");
  const paramList = columns.map((c) => `@${c}`).join(", ");
  const updateList = columns
    .filter((c) => c !== "id" && c !== "created_at")
    .map((c) => `${c} = @${c}`)
    .join(", ");
  return {
    get(tenantId: string, id: EntityId): T | undefined {
      const row = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ? AND id = ?`).get(tenantId, id) as Record<string, unknown> | undefined;
      return row ? fromRow(row) : undefined;
    },
    put(tenantId: string, entity: T): void {
      const params = toParams(tenantId, entity);
      db.prepare(`INSERT INTO ${table} (${colList}) VALUES (${paramList}) ON CONFLICT(id) DO UPDATE SET ${updateList}`).run(params);
    },
    list(tenantId: string): readonly T[] {
      const rows = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ?`).all(tenantId) as Record<string, unknown>[];
      return rows.map(fromRow);
    },
    delete(tenantId: string, id: EntityId): boolean {
      const result = db.prepare(`DELETE FROM ${table} WHERE tenant_id = ? AND id = ?`).run(tenantId, id);
      return result.changes > 0;
    },
  };
}

// ============================================================
// retail-barcode-scanning
// ============================================================
const BarcodeCrud = (db: DatabaseType) => makeCrud<Barcode>(db, {
  table: "retail_barcodes",
  columns: ["id", "tenant_id", "code", "format", "product_id", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    code: r.code as string,
    format: r.format as string,
    productId: r.product_id as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    code: e.code,
    format: e.format,
    product_id: e.productId,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteRetailBarcodeScanningStore implements RetailBarcodeScanningStore {
  constructor(private readonly db: DatabaseType) {}
  getBarcode(t: string, id: EntityId) { return BarcodeCrud(this.db).get(t, id); }
  putBarcode(t: string, e: Barcode) { BarcodeCrud(this.db).put(t, e); }
  listBarcodes(t: string) { return BarcodeCrud(this.db).list(t); }
  deleteBarcode(t: string, id: EntityId) { return BarcodeCrud(this.db).delete(t, id); }
}

// ============================================================
// retail-customer-management
// ============================================================
const CustomerCrud = (db: DatabaseType) => makeCrud<Customer>(db, {
  table: "retail_customers",
  columns: ["id", "tenant_id", "name", "phone", "email", "address", "loyalty_notes", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    phone: (r.phone as string | null) ?? null,
    email: (r.email as string | null) ?? null,
    address: (r.address as string | null) ?? null,
    loyaltyNotes: (r.loyalty_notes as string | null) ?? null,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    phone: e.phone,
    email: e.email,
    address: e.address,
    loyalty_notes: e.loyaltyNotes,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteRetailCustomerManagementStore implements RetailCustomerManagementStore {
  constructor(private readonly db: DatabaseType) {}
  getCustomer(t: string, id: EntityId) { return CustomerCrud(this.db).get(t, id); }
  putCustomer(t: string, e: Customer) { CustomerCrud(this.db).put(t, e); }
  listCustomers(t: string) { return CustomerCrud(this.db).list(t); }
  deleteCustomer(t: string, id: EntityId) { return CustomerCrud(this.db).delete(t, id); }
}

// ============================================================
// retail-inventory
// ============================================================
const Stock_levelCrud = (db: DatabaseType) => makeCrud<StockLevel>(db, {
  table: "retail_stock_levels",
  columns: ["id", "tenant_id", "product_id", "quantity", "low_stock_threshold", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    productId: r.product_id as string,
    quantity: r.quantity as number,
    lowStockThreshold: r.low_stock_threshold as number,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    product_id: e.productId,
    quantity: e.quantity,
    low_stock_threshold: e.lowStockThreshold,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const Stock_movementCrud = (db: DatabaseType) => makeCrud<StockMovement>(db, {
  table: "retail_stock_movements",
  columns: ["id", "tenant_id", "product_id", "delta", "reason", "reference", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    productId: r.product_id as string,
    delta: r.delta as number,
    reason: r.reason as string,
    reference: (r.reference as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    product_id: e.productId,
    delta: e.delta,
    reason: e.reason,
    reference: e.reference,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteRetailInventoryStore implements RetailInventoryStore {
  constructor(private readonly db: DatabaseType) {}
  getStockLevel(t: string, id: EntityId) { return Stock_levelCrud(this.db).get(t, id); }
  putStockLevel(t: string, e: StockLevel) { Stock_levelCrud(this.db).put(t, e); }
  listStockLevels(t: string) { return Stock_levelCrud(this.db).list(t); }
  deleteStockLevel(t: string, id: EntityId) { return Stock_levelCrud(this.db).delete(t, id); }
  getStockMovement(t: string, id: EntityId) { return Stock_movementCrud(this.db).get(t, id); }
  putStockMovement(t: string, e: StockMovement) { Stock_movementCrud(this.db).put(t, e); }
  listStockMovements(t: string) { return Stock_movementCrud(this.db).list(t); }
  deleteStockMovement(t: string, id: EntityId) { return Stock_movementCrud(this.db).delete(t, id); }
}

// ============================================================
// retail-point-of-sale
// ============================================================
const SaleCrud = (db: DatabaseType) => makeCrud<Sale>(db, {
  table: "retail_sales",
  columns: ["id", "tenant_id", "cart_json", "subtotal_cents", "discount_cents", "tax_cents", "total_cents", "currency", "payment_id", "receipt_document_id", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    cartJson: r.cart_json as string,
    subtotalCents: r.subtotal_cents as number,
    discountCents: r.discount_cents as number,
    taxCents: r.tax_cents as number,
    totalCents: r.total_cents as number,
    currency: r.currency as string,
    paymentId: (r.payment_id as string | null) ?? null,
    receiptDocumentId: (r.receipt_document_id as string | null) ?? null,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    cart_json: e.cartJson,
    subtotal_cents: e.subtotalCents,
    discount_cents: e.discountCents,
    tax_cents: e.taxCents,
    total_cents: e.totalCents,
    currency: e.currency,
    payment_id: e.paymentId,
    receipt_document_id: e.receiptDocumentId,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteRetailPointOfSaleStore implements RetailPointOfSaleStore {
  constructor(private readonly db: DatabaseType) {}
  getSale(t: string, id: EntityId) { return SaleCrud(this.db).get(t, id); }
  putSale(t: string, e: Sale) { SaleCrud(this.db).put(t, e); }
  listSales(t: string) { return SaleCrud(this.db).list(t); }
  deleteSale(t: string, id: EntityId) { return SaleCrud(this.db).delete(t, id); }
}

// ============================================================
// retail-product-catalog
// ============================================================
const CategoryCrud = (db: DatabaseType) => makeCrud<Category>(db, {
  table: "retail_categories",
  columns: ["id", "tenant_id", "name", "description", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    description: (r.description as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    description: e.description,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const ProductCrud = (db: DatabaseType) => makeCrud<Product>(db, {
  table: "retail_products",
  columns: ["id", "tenant_id", "name", "sku", "category_id", "price_cents", "currency", "description", "photo_document_id", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    sku: r.sku as string,
    categoryId: r.category_id as string,
    priceCents: r.price_cents as number,
    currency: r.currency as string,
    description: (r.description as string | null) ?? null,
    photoDocumentId: (r.photo_document_id as string | null) ?? null,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    sku: e.sku,
    category_id: e.categoryId,
    price_cents: e.priceCents,
    currency: e.currency,
    description: e.description,
    photo_document_id: e.photoDocumentId,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteRetailProductCatalogStore implements RetailProductCatalogStore {
  constructor(private readonly db: DatabaseType) {}
  getCategory(t: string, id: EntityId) { return CategoryCrud(this.db).get(t, id); }
  putCategory(t: string, e: Category) { CategoryCrud(this.db).put(t, e); }
  listCategorys(t: string) { return CategoryCrud(this.db).list(t); }
  deleteCategory(t: string, id: EntityId) { return CategoryCrud(this.db).delete(t, id); }
  getProduct(t: string, id: EntityId) { return ProductCrud(this.db).get(t, id); }
  putProduct(t: string, e: Product) { ProductCrud(this.db).put(t, e); }
  listProducts(t: string) { return ProductCrud(this.db).list(t); }
  deleteProduct(t: string, id: EntityId) { return ProductCrud(this.db).delete(t, id); }
}

// ============================================================
// retail-promotions
// ============================================================
const PromotionCrud = (db: DatabaseType) => makeCrud<Promotion>(db, {
  table: "retail_promotions",
  columns: ["id", "tenant_id", "name", "discount_type", "discount_value", "scope_json", "starts_at", "ends_at", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    discountType: r.discount_type as string,
    discountValue: r.discount_value as number,
    scopeJson: r.scope_json as string,
    startsAt: r.starts_at as string,
    endsAt: r.ends_at as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    discount_type: e.discountType,
    discount_value: e.discountValue,
    scope_json: e.scopeJson,
    starts_at: e.startsAt,
    ends_at: e.endsAt,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteRetailPromotionsStore implements RetailPromotionsStore {
  constructor(private readonly db: DatabaseType) {}
  getPromotion(t: string, id: EntityId) { return PromotionCrud(this.db).get(t, id); }
  putPromotion(t: string, e: Promotion) { PromotionCrud(this.db).put(t, e); }
  listPromotions(t: string) { return PromotionCrud(this.db).list(t); }
  deletePromotion(t: string, id: EntityId) { return PromotionCrud(this.db).delete(t, id); }
}

// ============================================================
// retail-sales-reports
// ============================================================
const Sale_recordCrud = (db: DatabaseType) => makeCrud<SaleRecord>(db, {
  table: "retail_sale_records",
  columns: ["id", "tenant_id", "total_cents", "discount_cents", "tax_cents", "currency", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    totalCents: r.total_cents as number,
    discountCents: r.discount_cents as number,
    taxCents: r.tax_cents as number,
    currency: r.currency as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    total_cents: e.totalCents,
    discount_cents: e.discountCents,
    tax_cents: e.taxCents,
    currency: e.currency,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const Daily_sales_summaryCrud = (db: DatabaseType) => makeCrud<DailySalesSummary>(db, {
  table: "retail_daily_sales_summaries",
  columns: ["id", "tenant_id", "date", "total_sales_count", "total_revenue_cents", "total_discount_cents", "total_tax_cents", "average_basket_cents", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    date: r.date as string,
    totalSalesCount: r.total_sales_count as number,
    totalRevenueCents: r.total_revenue_cents as number,
    totalDiscountCents: r.total_discount_cents as number,
    totalTaxCents: r.total_tax_cents as number,
    averageBasketCents: r.average_basket_cents as number,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    date: e.date,
    total_sales_count: e.totalSalesCount,
    total_revenue_cents: e.totalRevenueCents,
    total_discount_cents: e.totalDiscountCents,
    total_tax_cents: e.totalTaxCents,
    average_basket_cents: e.averageBasketCents,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteRetailSalesReportsStore implements RetailSalesReportsStore {
  constructor(private readonly db: DatabaseType) {}
  getSaleRecord(t: string, id: EntityId) { return Sale_recordCrud(this.db).get(t, id); }
  putSaleRecord(t: string, e: SaleRecord) { Sale_recordCrud(this.db).put(t, e); }
  listSaleRecords(t: string) { return Sale_recordCrud(this.db).list(t); }
  deleteSaleRecord(t: string, id: EntityId) { return Sale_recordCrud(this.db).delete(t, id); }
  getDailySalesSummary(t: string, id: EntityId) { return Daily_sales_summaryCrud(this.db).get(t, id); }
  putDailySalesSummary(t: string, e: DailySalesSummary) { Daily_sales_summaryCrud(this.db).put(t, e); }
  listDailySalesSummarys(t: string) { return Daily_sales_summaryCrud(this.db).list(t); }
  deleteDailySalesSummary(t: string, id: EntityId) { return Daily_sales_summaryCrud(this.db).delete(t, id); }
}

// ============================================================
// retail-stock-alerts
// ============================================================
const Stock_alertCrud = (db: DatabaseType) => makeCrud<StockAlert>(db, {
  table: "retail_stock_alerts",
  columns: ["id", "tenant_id", "product_id", "alert_type", "current_quantity", "threshold", "notification_id", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    productId: r.product_id as string,
    alertType: r.alert_type as string,
    currentQuantity: r.current_quantity as number,
    threshold: r.threshold as number,
    notificationId: (r.notification_id as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    product_id: e.productId,
    alert_type: e.alertType,
    current_quantity: e.currentQuantity,
    threshold: e.threshold,
    notification_id: e.notificationId,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteRetailStockAlertsStore implements RetailStockAlertsStore {
  constructor(private readonly db: DatabaseType) {}
  getStockAlert(t: string, id: EntityId) { return Stock_alertCrud(this.db).get(t, id); }
  putStockAlert(t: string, e: StockAlert) { Stock_alertCrud(this.db).put(t, e); }
  listStockAlerts(t: string) { return Stock_alertCrud(this.db).list(t); }
  deleteStockAlert(t: string, id: EntityId) { return Stock_alertCrud(this.db).delete(t, id); }
}

// ============================================================
// retail-supplier-management
// ============================================================
const SupplierCrud = (db: DatabaseType) => makeCrud<Supplier>(db, {
  table: "retail_suppliers",
  columns: ["id", "tenant_id", "name", "contact_name", "phone", "email", "address", "payment_terms_days", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    contactName: (r.contact_name as string | null) ?? null,
    phone: (r.phone as string | null) ?? null,
    email: (r.email as string | null) ?? null,
    address: (r.address as string | null) ?? null,
    paymentTermsDays: r.payment_terms_days as number,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    contact_name: e.contactName,
    phone: e.phone,
    email: e.email,
    address: e.address,
    payment_terms_days: e.paymentTermsDays,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const Purchase_orderCrud = (db: DatabaseType) => makeCrud<PurchaseOrder>(db, {
  table: "retail_purchase_orders",
  columns: ["id", "tenant_id", "supplier_id", "items_json", "total_cents", "currency", "status", "received_at", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    supplierId: r.supplier_id as string,
    itemsJson: r.items_json as string,
    totalCents: r.total_cents as number,
    currency: r.currency as string,
    status: r.status as string,
    receivedAt: (r.received_at as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    supplier_id: e.supplierId,
    items_json: e.itemsJson,
    total_cents: e.totalCents,
    currency: e.currency,
    status: e.status,
    received_at: e.receivedAt,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteRetailSupplierManagementStore implements RetailSupplierManagementStore {
  constructor(private readonly db: DatabaseType) {}
  getSupplier(t: string, id: EntityId) { return SupplierCrud(this.db).get(t, id); }
  putSupplier(t: string, e: Supplier) { SupplierCrud(this.db).put(t, e); }
  listSuppliers(t: string) { return SupplierCrud(this.db).list(t); }
  deleteSupplier(t: string, id: EntityId) { return SupplierCrud(this.db).delete(t, id); }
  getPurchaseOrder(t: string, id: EntityId) { return Purchase_orderCrud(this.db).get(t, id); }
  putPurchaseOrder(t: string, e: PurchaseOrder) { Purchase_orderCrud(this.db).put(t, e); }
  listPurchaseOrders(t: string) { return Purchase_orderCrud(this.db).list(t); }
  deletePurchaseOrder(t: string, id: EntityId) { return Purchase_orderCrud(this.db).delete(t, id); }
}
