/**
 * SQLite store implementations for all 10 schools components.
 * Auto-generated by scripts/generate_vertical_stores.py.
 *
 * Each class implements the corresponding component's Store interface,
 * backed by a SQLite table. All data is tenant-scoped.
 */

import type { DatabaseType } from "../../database";
import type { EntityId, TenantId } from "@business-os/shared";

import type { AttendanceRecord, SchoolAttendanceStore } from "@business-os/components/schools/school-attendance/backend";
import type { Certificate, SchoolCertificatesStore } from "@business-os/components/schools/school-certificates/backend";
import type { ClassSession, SchoolClassSchedulingStore } from "@business-os/components/schools/school-class-scheduling/backend";
import type { Exam, SchoolExamsStore } from "@business-os/components/schools/school-exams/backend";
import type { Grade, Assessment, SchoolGradingStore } from "@business-os/components/schools/school-grading/backend";
import type { ParentMessage, SchoolParentCommunicationStore } from "@business-os/components/schools/school-parent-communication/backend";
import type { Student, SchoolStudentEnrollmentStore } from "@business-os/components/schools/school-student-enrollment/backend";
import type { StudentPortalSession, SchoolStudentPortalStore } from "@business-os/components/schools/school-student-portal/backend";
import type { Teacher, SchoolTeacherManagementStore } from "@business-os/components/schools/school-teacher-management/backend";
import type { TuitionPlan, TuitionPayment, SchoolTuitionManagementStore } from "@business-os/components/schools/school-tuition-management/backend";

// ============================================================
// Helper: generic CRUD factory
// ============================================================
function makeCrud<T>(db: DatabaseType, config: {
  table: string;
  columns: readonly string[];
  fromRow: (row: Record<string, unknown>) => T;
  toParams: (tenantId: string, entity: T) => Record<string, unknown>;
}) {
  const { table, columns, fromRow, toParams } = config;
  const colList = columns.join(", ");
  const paramList = columns.map((c) => `@${c}`).join(", ");
  const updateList = columns
    .filter((c) => c !== "id" && c !== "created_at")
    .map((c) => `${c} = @${c}`)
    .join(", ");
  return {
    get(tenantId: string, id: EntityId): T | undefined {
      const row = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ? AND id = ?`).get(tenantId, id) as Record<string, unknown> | undefined;
      return row ? fromRow(row) : undefined;
    },
    put(tenantId: string, entity: T): void {
      const params = toParams(tenantId, entity);
      db.prepare(`INSERT INTO ${table} (${colList}) VALUES (${paramList}) ON CONFLICT(id) DO UPDATE SET ${updateList}`).run(params);
    },
    list(tenantId: string): readonly T[] {
      const rows = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ?`).all(tenantId) as Record<string, unknown>[];
      return rows.map(fromRow);
    },
    delete(tenantId: string, id: EntityId): boolean {
      const result = db.prepare(`DELETE FROM ${table} WHERE tenant_id = ? AND id = ?`).run(tenantId, id);
      return result.changes > 0;
    },
  };
}

// ============================================================
// school-attendance
// ============================================================
const Attendance_recordCrud = (db: DatabaseType) => makeCrud<AttendanceRecord>(db, {
  table: "school_attendance_records",
  columns: ["id", "tenant_id", "student_id", "session_date", "status", "notes", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    studentId: r.student_id as string,
    sessionDate: r.session_date as string,
    status: r.status as string,
    notes: (r.notes as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    student_id: e.studentId,
    session_date: e.sessionDate,
    status: e.status,
    notes: e.notes,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteSchoolAttendanceStore implements SchoolAttendanceStore {
  constructor(private readonly db: DatabaseType) {}
  getAttendanceRecord(t: string, id: EntityId) { return Attendance_recordCrud(this.db).get(t, id); }
  putAttendanceRecord(t: string, e: AttendanceRecord) { Attendance_recordCrud(this.db).put(t, e); }
  listAttendanceRecords(t: string) { return Attendance_recordCrud(this.db).list(t); }
  deleteAttendanceRecord(t: string, id: EntityId) { return Attendance_recordCrud(this.db).delete(t, id); }
}

// ============================================================
// school-certificates
// ============================================================
const CertificateCrud = (db: DatabaseType) => makeCrud<Certificate>(db, {
  table: "school_certificates",
  columns: ["id", "tenant_id", "student_id", "program_name", "certificate_number", "issued_at", "pdf_document_id", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    studentId: r.student_id as string,
    programName: r.program_name as string,
    certificateNumber: r.certificate_number as string,
    issuedAt: r.issued_at as string,
    pdfDocumentId: (r.pdf_document_id as string | null) ?? null,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    student_id: e.studentId,
    program_name: e.programName,
    certificate_number: e.certificateNumber,
    issued_at: e.issuedAt,
    pdf_document_id: e.pdfDocumentId,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteSchoolCertificatesStore implements SchoolCertificatesStore {
  constructor(private readonly db: DatabaseType) {}
  getCertificate(t: string, id: EntityId) { return CertificateCrud(this.db).get(t, id); }
  putCertificate(t: string, e: Certificate) { CertificateCrud(this.db).put(t, e); }
  listCertificates(t: string) { return CertificateCrud(this.db).list(t); }
  deleteCertificate(t: string, id: EntityId) { return CertificateCrud(this.db).delete(t, id); }
}

// ============================================================
// school-class-scheduling
// ============================================================
const Class_sessionCrud = (db: DatabaseType) => makeCrud<ClassSession>(db, {
  table: "school_class_sessions",
  columns: ["id", "tenant_id", "subject", "teacher_user_id", "room_id", "day_of_week", "start_hour", "start_minute", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    subject: r.subject as string,
    teacherUserId: r.teacher_user_id as string,
    roomId: r.room_id as string,
    dayOfWeek: r.day_of_week as number,
    startHour: r.start_hour as number,
    startMinute: r.start_minute as number,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    subject: e.subject,
    teacher_user_id: e.teacherUserId,
    room_id: e.roomId,
    day_of_week: e.dayOfWeek,
    start_hour: e.startHour,
    start_minute: e.startMinute,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteSchoolClassSchedulingStore implements SchoolClassSchedulingStore {
  constructor(private readonly db: DatabaseType) {}
  getClassSession(t: string, id: EntityId) { return Class_sessionCrud(this.db).get(t, id); }
  putClassSession(t: string, e: ClassSession) { Class_sessionCrud(this.db).put(t, e); }
  listClassSessions(t: string) { return Class_sessionCrud(this.db).list(t); }
  deleteClassSession(t: string, id: EntityId) { return Class_sessionCrud(this.db).delete(t, id); }
}

// ============================================================
// school-exams
// ============================================================
const ExamCrud = (db: DatabaseType) => makeCrud<Exam>(db, {
  table: "school_exams",
  columns: ["id", "tenant_id", "name", "period", "starts_at", "ends_at", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    period: r.period as string,
    startsAt: r.starts_at as string,
    endsAt: r.ends_at as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    period: e.period,
    starts_at: e.startsAt,
    ends_at: e.endsAt,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteSchoolExamsStore implements SchoolExamsStore {
  constructor(private readonly db: DatabaseType) {}
  getExam(t: string, id: EntityId) { return ExamCrud(this.db).get(t, id); }
  putExam(t: string, e: Exam) { ExamCrud(this.db).put(t, e); }
  listExams(t: string) { return ExamCrud(this.db).list(t); }
  deleteExam(t: string, id: EntityId) { return ExamCrud(this.db).delete(t, id); }
}

// ============================================================
// school-grading
// ============================================================
const GradeCrud = (db: DatabaseType) => makeCrud<Grade>(db, {
  table: "school_grades",
  columns: ["id", "tenant_id", "student_id", "assessment_id", "score_pct", "notes", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    studentId: r.student_id as string,
    assessmentId: r.assessment_id as string,
    scorePct: r.score_pct as number,
    notes: (r.notes as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    student_id: e.studentId,
    assessment_id: e.assessmentId,
    score_pct: e.scorePct,
    notes: e.notes,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const AssessmentCrud = (db: DatabaseType) => makeCrud<Assessment>(db, {
  table: "school_assessments",
  columns: ["id", "tenant_id", "name", "subject", "max_score_pct", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    subject: r.subject as string,
    maxScorePct: r.max_score_pct as number,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    subject: e.subject,
    max_score_pct: e.maxScorePct,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteSchoolGradingStore implements SchoolGradingStore {
  constructor(private readonly db: DatabaseType) {}
  getGrade(t: string, id: EntityId) { return GradeCrud(this.db).get(t, id); }
  putGrade(t: string, e: Grade) { GradeCrud(this.db).put(t, e); }
  listGrades(t: string) { return GradeCrud(this.db).list(t); }
  deleteGrade(t: string, id: EntityId) { return GradeCrud(this.db).delete(t, id); }
  getAssessment(t: string, id: EntityId) { return AssessmentCrud(this.db).get(t, id); }
  putAssessment(t: string, e: Assessment) { AssessmentCrud(this.db).put(t, e); }
  listAssessments(t: string) { return AssessmentCrud(this.db).list(t); }
  deleteAssessment(t: string, id: EntityId) { return AssessmentCrud(this.db).delete(t, id); }
}

// ============================================================
// school-parent-communication
// ============================================================
const Parent_messageCrud = (db: DatabaseType) => makeCrud<ParentMessage>(db, {
  table: "school_parent_messages",
  columns: ["id", "tenant_id", "student_id", "subject", "body", "direction", "messaging_message_id", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    studentId: r.student_id as string,
    subject: r.subject as string,
    body: r.body as string,
    direction: r.direction as string,
    messagingMessageId: (r.messaging_message_id as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    student_id: e.studentId,
    subject: e.subject,
    body: e.body,
    direction: e.direction,
    messaging_message_id: e.messagingMessageId,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteSchoolParentCommunicationStore implements SchoolParentCommunicationStore {
  constructor(private readonly db: DatabaseType) {}
  getParentMessage(t: string, id: EntityId) { return Parent_messageCrud(this.db).get(t, id); }
  putParentMessage(t: string, e: ParentMessage) { Parent_messageCrud(this.db).put(t, e); }
  listParentMessages(t: string) { return Parent_messageCrud(this.db).list(t); }
  deleteParentMessage(t: string, id: EntityId) { return Parent_messageCrud(this.db).delete(t, id); }
}

// ============================================================
// school-student-enrollment
// ============================================================
const StudentCrud = (db: DatabaseType) => makeCrud<Student>(db, {
  table: "school_students",
  columns: ["id", "tenant_id", "first_name", "last_name", "date_of_birth", "guardian_name", "guardian_phone", "enrollment_status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    firstName: r.first_name as string,
    lastName: r.last_name as string,
    dateOfBirth: r.date_of_birth as string,
    guardianName: r.guardian_name as string,
    guardianPhone: (r.guardian_phone as string | null) ?? null,
    enrollmentStatus: r.enrollment_status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    first_name: e.firstName,
    last_name: e.lastName,
    date_of_birth: e.dateOfBirth,
    guardian_name: e.guardianName,
    guardian_phone: e.guardianPhone,
    enrollment_status: e.enrollmentStatus,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteSchoolStudentEnrollmentStore implements SchoolStudentEnrollmentStore {
  constructor(private readonly db: DatabaseType) {}
  getStudent(t: string, id: EntityId) { return StudentCrud(this.db).get(t, id); }
  putStudent(t: string, e: Student) { StudentCrud(this.db).put(t, e); }
  listStudents(t: string) { return StudentCrud(this.db).list(t); }
  deleteStudent(t: string, id: EntityId) { return StudentCrud(this.db).delete(t, id); }
}

// ============================================================
// school-student-portal
// ============================================================
const Student_portal_sessionCrud = (db: DatabaseType) => makeCrud<StudentPortalSession>(db, {
  table: "school_student_portal_sessions",
  columns: ["id", "tenant_id", "student_id", "started_at", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    studentId: r.student_id as string,
    startedAt: r.started_at as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    student_id: e.studentId,
    started_at: e.startedAt,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteSchoolStudentPortalStore implements SchoolStudentPortalStore {
  constructor(private readonly db: DatabaseType) {}
  getStudentPortalSession(t: string, id: EntityId) { return Student_portal_sessionCrud(this.db).get(t, id); }
  putStudentPortalSession(t: string, e: StudentPortalSession) { Student_portal_sessionCrud(this.db).put(t, e); }
  listStudentPortalSessions(t: string) { return Student_portal_sessionCrud(this.db).list(t); }
  deleteStudentPortalSession(t: string, id: EntityId) { return Student_portal_sessionCrud(this.db).delete(t, id); }
}

// ============================================================
// school-teacher-management
// ============================================================
const TeacherCrud = (db: DatabaseType) => makeCrud<Teacher>(db, {
  table: "school_teachers",
  columns: ["id", "tenant_id", "first_name", "last_name", "email", "phone", "subjects_json", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    firstName: r.first_name as string,
    lastName: r.last_name as string,
    email: (r.email as string | null) ?? null,
    phone: (r.phone as string | null) ?? null,
    subjectsJson: (r.subjects_json as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    first_name: e.firstName,
    last_name: e.lastName,
    email: e.email,
    phone: e.phone,
    subjects_json: e.subjectsJson,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteSchoolTeacherManagementStore implements SchoolTeacherManagementStore {
  constructor(private readonly db: DatabaseType) {}
  getTeacher(t: string, id: EntityId) { return TeacherCrud(this.db).get(t, id); }
  putTeacher(t: string, e: Teacher) { TeacherCrud(this.db).put(t, e); }
  listTeachers(t: string) { return TeacherCrud(this.db).list(t); }
  deleteTeacher(t: string, id: EntityId) { return TeacherCrud(this.db).delete(t, id); }
}

// ============================================================
// school-tuition-management
// ============================================================
const Tuition_planCrud = (db: DatabaseType) => makeCrud<TuitionPlan>(db, {
  table: "school_tuition_plans",
  columns: ["id", "tenant_id", "student_id", "total_amount_cents", "currency", "installments_json", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    studentId: r.student_id as string,
    totalAmountCents: r.total_amount_cents as number,
    currency: r.currency as string,
    installmentsJson: r.installments_json as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    student_id: e.studentId,
    total_amount_cents: e.totalAmountCents,
    currency: e.currency,
    installments_json: e.installmentsJson,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const Tuition_paymentCrud = (db: DatabaseType) => makeCrud<TuitionPayment>(db, {
  table: "school_tuition_payments",
  columns: ["id", "tenant_id", "plan_id", "amount_cents", "currency", "payment_reference", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    planId: r.plan_id as string,
    amountCents: r.amount_cents as number,
    currency: r.currency as string,
    paymentReference: (r.payment_reference as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    plan_id: e.planId,
    amount_cents: e.amountCents,
    currency: e.currency,
    payment_reference: e.paymentReference,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteSchoolTuitionManagementStore implements SchoolTuitionManagementStore {
  constructor(private readonly db: DatabaseType) {}
  getTuitionPlan(t: string, id: EntityId) { return Tuition_planCrud(this.db).get(t, id); }
  putTuitionPlan(t: string, e: TuitionPlan) { Tuition_planCrud(this.db).put(t, e); }
  listTuitionPlans(t: string) { return Tuition_planCrud(this.db).list(t); }
  deleteTuitionPlan(t: string, id: EntityId) { return Tuition_planCrud(this.db).delete(t, id); }
  getTuitionPayment(t: string, id: EntityId) { return Tuition_paymentCrud(this.db).get(t, id); }
  putTuitionPayment(t: string, e: TuitionPayment) { Tuition_paymentCrud(this.db).put(t, e); }
  listTuitionPayments(t: string) { return Tuition_paymentCrud(this.db).list(t); }
  deleteTuitionPayment(t: string, id: EntityId) { return Tuition_paymentCrud(this.db).delete(t, id); }
}
