/**
 * SQLite store implementations for all 8 service-businesses components.
 * Auto-generated by scripts/generate_vertical_stores.py.
 *
 * Each class implements the corresponding component's Store interface,
 * backed by a SQLite table. All data is tenant-scoped.
 */

import type { DatabaseType } from "../../database";
import type { EntityId, TenantId } from "@business-os/shared";

import type { Booking, ServiceBookingStore } from "@business-os/components/service-businesses/service-booking/backend";
import type { Service, ServiceCatalogStore } from "@business-os/components/service-businesses/service-catalog/backend";
import type { Customer, ServiceCustomerManagementStore } from "@business-os/components/service-businesses/service-customer-management/backend";
import type { Feedback, ServiceFeedbackStore } from "@business-os/components/service-businesses/service-feedback/backend";
import type { Invoice, ServiceInvoicingStore } from "@business-os/components/service-businesses/service-invoicing/backend";
import type { Job, JobTask, ServiceJobTrackingStore } from "@business-os/components/service-businesses/service-job-tracking/backend";
import type { Quote, ServiceQuotesStore } from "@business-os/components/service-businesses/service-quotes/backend";
import type { StaffAvailability, TimeOff, ServiceSchedulingStore } from "@business-os/components/service-businesses/service-scheduling/backend";

// ============================================================
// Helper: generic CRUD factory
// ============================================================
function makeCrud<T>(db: DatabaseType, config: {
  table: string;
  columns: readonly string[];
  fromRow: (row: Record<string, unknown>) => T;
  toParams: (tenantId: string, entity: T) => Record<string, unknown>;
}) {
  const { table, columns, fromRow, toParams } = config;
  const colList = columns.join(", ");
  const paramList = columns.map((c) => `@${c}`).join(", ");
  const updateList = columns
    .filter((c) => c !== "id" && c !== "created_at")
    .map((c) => `${c} = @${c}`)
    .join(", ");
  return {
    get(tenantId: string, id: EntityId): T | undefined {
      const row = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ? AND id = ?`).get(tenantId, id) as Record<string, unknown> | undefined;
      return row ? fromRow(row) : undefined;
    },
    put(tenantId: string, entity: T): void {
      const params = toParams(tenantId, entity);
      db.prepare(`INSERT INTO ${table} (${colList}) VALUES (${paramList}) ON CONFLICT(id) DO UPDATE SET ${updateList}`).run(params);
    },
    list(tenantId: string): readonly T[] {
      const rows = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ?`).all(tenantId) as Record<string, unknown>[];
      return rows.map(fromRow);
    },
    delete(tenantId: string, id: EntityId): boolean {
      const result = db.prepare(`DELETE FROM ${table} WHERE tenant_id = ? AND id = ?`).run(tenantId, id);
      return result.changes > 0;
    },
  };
}

// ============================================================
// service-booking
// ============================================================
const BookingCrud = (db: DatabaseType) => makeCrud<Booking>(db, {
  table: "service_bookings",
  columns: ["id", "tenant_id", "customer_id", "service_id", "staff_user_id", "scheduled_at", "duration_minutes", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    customerId: r.customer_id as string,
    serviceId: r.service_id as string,
    staffUserId: r.staff_user_id as string,
    scheduledAt: r.scheduled_at as string,
    durationMinutes: r.duration_minutes as number,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    customer_id: e.customerId,
    service_id: e.serviceId,
    staff_user_id: e.staffUserId,
    scheduled_at: e.scheduledAt,
    duration_minutes: e.durationMinutes,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteServiceBookingStore implements ServiceBookingStore {
  constructor(private readonly db: DatabaseType) {}
  getBooking(t: string, id: EntityId) { return BookingCrud(this.db).get(t, id); }
  putBooking(t: string, e: Booking) { BookingCrud(this.db).put(t, e); }
  listBookings(t: string) { return BookingCrud(this.db).list(t); }
  deleteBooking(t: string, id: EntityId) { return BookingCrud(this.db).delete(t, id); }
}

// ============================================================
// service-catalog
// ============================================================
const ServiceCrud = (db: DatabaseType) => makeCrud<Service>(db, {
  table: "service_services",
  columns: ["id", "tenant_id", "name", "description", "category_id", "price_cents", "currency", "duration_minutes", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    description: (r.description as string | null) ?? null,
    categoryId: r.category_id as string,
    priceCents: r.price_cents as number,
    currency: r.currency as string,
    durationMinutes: r.duration_minutes as number,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    description: e.description,
    category_id: e.categoryId,
    price_cents: e.priceCents,
    currency: e.currency,
    duration_minutes: e.durationMinutes,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteServiceCatalogStore implements ServiceCatalogStore {
  constructor(private readonly db: DatabaseType) {}
  getService(t: string, id: EntityId) { return ServiceCrud(this.db).get(t, id); }
  putService(t: string, e: Service) { ServiceCrud(this.db).put(t, e); }
  listServices(t: string) { return ServiceCrud(this.db).list(t); }
  deleteService(t: string, id: EntityId) { return ServiceCrud(this.db).delete(t, id); }
}

// ============================================================
// service-customer-management
// ============================================================
const CustomerCrud = (db: DatabaseType) => makeCrud<Customer>(db, {
  table: "service_customers",
  columns: ["id", "tenant_id", "name", "phone", "email", "address", "preferences_json", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    name: r.name as string,
    phone: (r.phone as string | null) ?? null,
    email: (r.email as string | null) ?? null,
    address: (r.address as string | null) ?? null,
    preferencesJson: (r.preferences_json as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    name: e.name,
    phone: e.phone,
    email: e.email,
    address: e.address,
    preferences_json: e.preferencesJson,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteServiceCustomerManagementStore implements ServiceCustomerManagementStore {
  constructor(private readonly db: DatabaseType) {}
  getCustomer(t: string, id: EntityId) { return CustomerCrud(this.db).get(t, id); }
  putCustomer(t: string, e: Customer) { CustomerCrud(this.db).put(t, e); }
  listCustomers(t: string) { return CustomerCrud(this.db).list(t); }
  deleteCustomer(t: string, id: EntityId) { return CustomerCrud(this.db).delete(t, id); }
}

// ============================================================
// service-feedback
// ============================================================
const FeedbackCrud = (db: DatabaseType) => makeCrud<Feedback>(db, {
  table: "service_feedbacks",
  columns: ["id", "tenant_id", "customer_id", "booking_id", "rating", "comment", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    customerId: r.customer_id as string,
    bookingId: r.booking_id as string,
    rating: r.rating as number,
    comment: (r.comment as string | null) ?? null,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    customer_id: e.customerId,
    booking_id: e.bookingId,
    rating: e.rating,
    comment: e.comment,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteServiceFeedbackStore implements ServiceFeedbackStore {
  constructor(private readonly db: DatabaseType) {}
  getFeedback(t: string, id: EntityId) { return FeedbackCrud(this.db).get(t, id); }
  putFeedback(t: string, e: Feedback) { FeedbackCrud(this.db).put(t, e); }
  listFeedbacks(t: string) { return FeedbackCrud(this.db).list(t); }
  deleteFeedback(t: string, id: EntityId) { return FeedbackCrud(this.db).delete(t, id); }
}

// ============================================================
// service-invoicing
// ============================================================
const InvoiceCrud = (db: DatabaseType) => makeCrud<Invoice>(db, {
  table: "service_invoices",
  columns: ["id", "tenant_id", "customer_id", "booking_id", "job_id", "subtotal_cents", "tax_cents", "total_cents", "currency", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    customerId: r.customer_id as string,
    bookingId: (r.booking_id as string | null) ?? null,
    jobId: (r.job_id as string | null) ?? null,
    subtotalCents: r.subtotal_cents as number,
    taxCents: r.tax_cents as number,
    totalCents: r.total_cents as number,
    currency: r.currency as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    customer_id: e.customerId,
    booking_id: e.bookingId,
    job_id: e.jobId,
    subtotal_cents: e.subtotalCents,
    tax_cents: e.taxCents,
    total_cents: e.totalCents,
    currency: e.currency,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteServiceInvoicingStore implements ServiceInvoicingStore {
  constructor(private readonly db: DatabaseType) {}
  getInvoice(t: string, id: EntityId) { return InvoiceCrud(this.db).get(t, id); }
  putInvoice(t: string, e: Invoice) { InvoiceCrud(this.db).put(t, e); }
  listInvoices(t: string) { return InvoiceCrud(this.db).list(t); }
  deleteInvoice(t: string, id: EntityId) { return InvoiceCrud(this.db).delete(t, id); }
}

// ============================================================
// service-job-tracking
// ============================================================
const JobCrud = (db: DatabaseType) => makeCrud<Job>(db, {
  table: "service_jobs",
  columns: ["id", "tenant_id", "booking_id", "customer_id", "title", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    bookingId: (r.booking_id as string | null) ?? null,
    customerId: r.customer_id as string,
    title: r.title as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    booking_id: e.bookingId,
    customer_id: e.customerId,
    title: e.title,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const Job_taskCrud = (db: DatabaseType) => makeCrud<JobTask>(db, {
  table: "service_job_tasks",
  columns: ["id", "tenant_id", "job_id", "title", "sort_order", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    jobId: r.job_id as string,
    title: r.title as string,
    order: r.sort_order as number,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    job_id: e.jobId,
    title: e.title,
    sort_order: e.order,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteServiceJobTrackingStore implements ServiceJobTrackingStore {
  constructor(private readonly db: DatabaseType) {}
  getJob(t: string, id: EntityId) { return JobCrud(this.db).get(t, id); }
  putJob(t: string, e: Job) { JobCrud(this.db).put(t, e); }
  listJobs(t: string) { return JobCrud(this.db).list(t); }
  deleteJob(t: string, id: EntityId) { return JobCrud(this.db).delete(t, id); }
  getJobTask(t: string, id: EntityId) { return Job_taskCrud(this.db).get(t, id); }
  putJobTask(t: string, e: JobTask) { Job_taskCrud(this.db).put(t, e); }
  listJobTasks(t: string) { return Job_taskCrud(this.db).list(t); }
  deleteJobTask(t: string, id: EntityId) { return Job_taskCrud(this.db).delete(t, id); }
}

// ============================================================
// service-quotes
// ============================================================
const QuoteCrud = (db: DatabaseType) => makeCrud<Quote>(db, {
  table: "service_quotes",
  columns: ["id", "tenant_id", "customer_name", "customer_phone", "items_json", "total_cents", "currency", "expires_at", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    customerName: r.customer_name as string,
    customerPhone: (r.customer_phone as string | null) ?? null,
    itemsJson: r.items_json as string,
    totalCents: r.total_cents as number,
    currency: r.currency as string,
    expiresAt: r.expires_at as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    customer_name: e.customerName,
    customer_phone: e.customerPhone,
    items_json: e.itemsJson,
    total_cents: e.totalCents,
    currency: e.currency,
    expires_at: e.expiresAt,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteServiceQuotesStore implements ServiceQuotesStore {
  constructor(private readonly db: DatabaseType) {}
  getQuote(t: string, id: EntityId) { return QuoteCrud(this.db).get(t, id); }
  putQuote(t: string, e: Quote) { QuoteCrud(this.db).put(t, e); }
  listQuotes(t: string) { return QuoteCrud(this.db).list(t); }
  deleteQuote(t: string, id: EntityId) { return QuoteCrud(this.db).delete(t, id); }
}

// ============================================================
// service-scheduling
// ============================================================
const Staff_availabilityCrud = (db: DatabaseType) => makeCrud<StaffAvailability>(db, {
  table: "service_staff_availabilities",
  columns: ["id", "tenant_id", "staff_user_id", "day_of_week", "start_hour", "end_hour", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    staffUserId: r.staff_user_id as string,
    dayOfWeek: r.day_of_week as number,
    startHour: r.start_hour as number,
    endHour: r.end_hour as number,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    staff_user_id: e.staffUserId,
    day_of_week: e.dayOfWeek,
    start_hour: e.startHour,
    end_hour: e.endHour,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

const Time_offCrud = (db: DatabaseType) => makeCrud<TimeOff>(db, {
  table: "service_time_offs",
  columns: ["id", "tenant_id", "staff_user_id", "starts_at", "ends_at", "reason", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    staffUserId: r.staff_user_id as string,
    startsAt: r.starts_at as string,
    endsAt: r.ends_at as string,
    reason: (r.reason as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    staff_user_id: e.staffUserId,
    starts_at: e.startsAt,
    ends_at: e.endsAt,
    reason: e.reason,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteServiceSchedulingStore implements ServiceSchedulingStore {
  constructor(private readonly db: DatabaseType) {}
  getStaffAvailability(t: string, id: EntityId) { return Staff_availabilityCrud(this.db).get(t, id); }
  putStaffAvailability(t: string, e: StaffAvailability) { Staff_availabilityCrud(this.db).put(t, e); }
  listStaffAvailabilitys(t: string) { return Staff_availabilityCrud(this.db).list(t); }
  deleteStaffAvailability(t: string, id: EntityId) { return Staff_availabilityCrud(this.db).delete(t, id); }
  getTimeOff(t: string, id: EntityId) { return Time_offCrud(this.db).get(t, id); }
  putTimeOff(t: string, e: TimeOff) { Time_offCrud(this.db).put(t, e); }
  listTimeOffs(t: string) { return Time_offCrud(this.db).list(t); }
  deleteTimeOff(t: string, id: EntityId) { return Time_offCrud(this.db).delete(t, id); }
}
