/**
 * SQLite store implementations for all 10 clinics components.
 * Auto-generated by scripts/generate_vertical_stores.py.
 *
 * Each class implements the corresponding component's Store interface,
 * backed by a SQLite table. All data is tenant-scoped.
 */

import type { DatabaseType } from "../../database";
import type { EntityId, TenantId } from "@business-os/shared";

import type { Appointment, ClinicAppointmentsStore } from "@business-os/components/clinics/clinic-appointments/backend";
import type { Invoice, ClinicBillingStore } from "@business-os/components/clinics/clinic-billing/backend";
import type { ConsentRecord, ClinicConsentStore } from "@business-os/components/clinics/clinic-consent/backend";
import type { LabOrder, ClinicLabOrdersStore } from "@business-os/components/clinics/clinic-lab-orders/backend";
import type { MedicalRecord, ClinicMedicalRecordsStore } from "@business-os/components/clinics/clinic-medical-records/backend";
import type { Patient, ClinicPatientManagementStore } from "@business-os/components/clinics/clinic-patient-management/backend";
import type { Prescription, ClinicPrescriptionsStore } from "@business-os/components/clinics/clinic-prescriptions/backend";
import type { Reminder, ClinicRemindersStore } from "@business-os/components/clinics/clinic-reminders/backend";
import type { Staff, ClinicStaffManagementStore } from "@business-os/components/clinics/clinic-staff-management/backend";
import type { TriageEntry, ClinicTriageStore } from "@business-os/components/clinics/clinic-triage/backend";

// ============================================================
// Helper: generic CRUD factory
// ============================================================
function makeCrud<T>(db: DatabaseType, config: {
  table: string;
  columns: readonly string[];
  fromRow: (row: Record<string, unknown>) => T;
  toParams: (tenantId: string, entity: T) => Record<string, unknown>;
}) {
  const { table, columns, fromRow, toParams } = config;
  const colList = columns.join(", ");
  const paramList = columns.map((c) => `@${c}`).join(", ");
  const updateList = columns
    .filter((c) => c !== "id" && c !== "created_at")
    .map((c) => `${c} = @${c}`)
    .join(", ");
  return {
    get(tenantId: string, id: EntityId): T | undefined {
      const row = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ? AND id = ?`).get(tenantId, id) as Record<string, unknown> | undefined;
      return row ? fromRow(row) : undefined;
    },
    put(tenantId: string, entity: T): void {
      const params = toParams(tenantId, entity);
      db.prepare(`INSERT INTO ${table} (${colList}) VALUES (${paramList}) ON CONFLICT(id) DO UPDATE SET ${updateList}`).run(params);
    },
    list(tenantId: string): readonly T[] {
      const rows = db.prepare(`SELECT ${colList} FROM ${table} WHERE tenant_id = ?`).all(tenantId) as Record<string, unknown>[];
      return rows.map(fromRow);
    },
    delete(tenantId: string, id: EntityId): boolean {
      const result = db.prepare(`DELETE FROM ${table} WHERE tenant_id = ? AND id = ?`).run(tenantId, id);
      return result.changes > 0;
    },
  };
}

// ============================================================
// clinic-appointments
// ============================================================
const AppointmentCrud = (db: DatabaseType) => makeCrud<Appointment>(db, {
  table: "clinic_appointments",
  columns: ["id", "tenant_id", "patient_id", "doctor_staff_id", "scheduled_at", "duration_minutes", "reason", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    patientId: r.patient_id as string,
    doctorStaffId: r.doctor_staff_id as string,
    scheduledAt: r.scheduled_at as string,
    durationMinutes: r.duration_minutes as number,
    reason: (r.reason as string | null) ?? null,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    patient_id: e.patientId,
    doctor_staff_id: e.doctorStaffId,
    scheduled_at: e.scheduledAt,
    duration_minutes: e.durationMinutes,
    reason: e.reason,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteClinicAppointmentsStore implements ClinicAppointmentsStore {
  constructor(private readonly db: DatabaseType) {}
  getAppointment(t: string, id: EntityId) { return AppointmentCrud(this.db).get(t, id); }
  putAppointment(t: string, e: Appointment) { AppointmentCrud(this.db).put(t, e); }
  listAppointments(t: string) { return AppointmentCrud(this.db).list(t); }
  deleteAppointment(t: string, id: EntityId) { return AppointmentCrud(this.db).delete(t, id); }
}

// ============================================================
// clinic-billing
// ============================================================
const InvoiceCrud = (db: DatabaseType) => makeCrud<Invoice>(db, {
  table: "clinic_invoices",
  columns: ["id", "tenant_id", "patient_id", "appointment_id", "amount_cents", "currency", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    patientId: r.patient_id as string,
    appointmentId: (r.appointment_id as string | null) ?? null,
    amountCents: r.amount_cents as number,
    currency: r.currency as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    patient_id: e.patientId,
    appointment_id: e.appointmentId,
    amount_cents: e.amountCents,
    currency: e.currency,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteClinicBillingStore implements ClinicBillingStore {
  constructor(private readonly db: DatabaseType) {}
  getInvoice(t: string, id: EntityId) { return InvoiceCrud(this.db).get(t, id); }
  putInvoice(t: string, e: Invoice) { InvoiceCrud(this.db).put(t, e); }
  listInvoices(t: string) { return InvoiceCrud(this.db).list(t); }
  deleteInvoice(t: string, id: EntityId) { return InvoiceCrud(this.db).delete(t, id); }
}

// ============================================================
// clinic-consent
// ============================================================
const Consent_recordCrud = (db: DatabaseType) => makeCrud<ConsentRecord>(db, {
  table: "clinic_consent_records",
  columns: ["id", "tenant_id", "patient_id", "purpose", "granted_at", "revoked_at", "revoke_reason", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    patientId: r.patient_id as string,
    purpose: r.purpose as string,
    grantedAt: r.granted_at as string,
    revokedAt: (r.revoked_at as string | null) ?? null,
    revokeReason: (r.revoke_reason as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    patient_id: e.patientId,
    purpose: e.purpose,
    granted_at: e.grantedAt,
    revoked_at: e.revokedAt,
    revoke_reason: e.revokeReason,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteClinicConsentStore implements ClinicConsentStore {
  constructor(private readonly db: DatabaseType) {}
  getConsentRecord(t: string, id: EntityId) { return Consent_recordCrud(this.db).get(t, id); }
  putConsentRecord(t: string, e: ConsentRecord) { Consent_recordCrud(this.db).put(t, e); }
  listConsentRecords(t: string) { return Consent_recordCrud(this.db).list(t); }
  deleteConsentRecord(t: string, id: EntityId) { return Consent_recordCrud(this.db).delete(t, id); }
}

// ============================================================
// clinic-lab-orders
// ============================================================
const Lab_orderCrud = (db: DatabaseType) => makeCrud<LabOrder>(db, {
  table: "clinic_lab_orders",
  columns: ["id", "tenant_id", "patient_id", "doctor_staff_id", "test_name", "status", "result_document_id", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    patientId: r.patient_id as string,
    doctorStaffId: r.doctor_staff_id as string,
    testName: r.test_name as string,
    status: r.status as string,
    resultDocumentId: (r.result_document_id as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    patient_id: e.patientId,
    doctor_staff_id: e.doctorStaffId,
    test_name: e.testName,
    status: e.status,
    result_document_id: e.resultDocumentId,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteClinicLabOrdersStore implements ClinicLabOrdersStore {
  constructor(private readonly db: DatabaseType) {}
  getLabOrder(t: string, id: EntityId) { return Lab_orderCrud(this.db).get(t, id); }
  putLabOrder(t: string, e: LabOrder) { Lab_orderCrud(this.db).put(t, e); }
  listLabOrders(t: string) { return Lab_orderCrud(this.db).list(t); }
  deleteLabOrder(t: string, id: EntityId) { return Lab_orderCrud(this.db).delete(t, id); }
}

// ============================================================
// clinic-medical-records
// ============================================================
const Medical_recordCrud = (db: DatabaseType) => makeCrud<MedicalRecord>(db, {
  table: "clinic_medical_records",
  columns: ["id", "tenant_id", "patient_id", "doctor_staff_id", "appointment_id", "consultation_notes", "diagnosis", "treatment_plan", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    patientId: r.patient_id as string,
    doctorStaffId: r.doctor_staff_id as string,
    appointmentId: (r.appointment_id as string | null) ?? null,
    consultationNotes: r.consultation_notes as string,
    diagnosis: (r.diagnosis as string | null) ?? null,
    treatmentPlan: (r.treatment_plan as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    patient_id: e.patientId,
    doctor_staff_id: e.doctorStaffId,
    appointment_id: e.appointmentId,
    consultation_notes: e.consultationNotes,
    diagnosis: e.diagnosis,
    treatment_plan: e.treatmentPlan,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteClinicMedicalRecordsStore implements ClinicMedicalRecordsStore {
  constructor(private readonly db: DatabaseType) {}
  getMedicalRecord(t: string, id: EntityId) { return Medical_recordCrud(this.db).get(t, id); }
  putMedicalRecord(t: string, e: MedicalRecord) { Medical_recordCrud(this.db).put(t, e); }
  listMedicalRecords(t: string) { return Medical_recordCrud(this.db).list(t); }
  deleteMedicalRecord(t: string, id: EntityId) { return Medical_recordCrud(this.db).delete(t, id); }
}

// ============================================================
// clinic-patient-management
// ============================================================
const PatientCrud = (db: DatabaseType) => makeCrud<Patient>(db, {
  table: "clinic_patients",
  columns: ["id", "tenant_id", "first_name", "last_name", "date_of_birth", "phone", "email", "address", "medical_record_number", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    firstName: r.first_name as string,
    lastName: r.last_name as string,
    dateOfBirth: r.date_of_birth as string,
    phone: (r.phone as string | null) ?? null,
    email: (r.email as string | null) ?? null,
    address: (r.address as string | null) ?? null,
    medicalRecordNumber: r.medical_record_number as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    first_name: e.firstName,
    last_name: e.lastName,
    date_of_birth: e.dateOfBirth,
    phone: e.phone,
    email: e.email,
    address: e.address,
    medical_record_number: e.medicalRecordNumber,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteClinicPatientManagementStore implements ClinicPatientManagementStore {
  constructor(private readonly db: DatabaseType) {}
  getPatient(t: string, id: EntityId) { return PatientCrud(this.db).get(t, id); }
  putPatient(t: string, e: Patient) { PatientCrud(this.db).put(t, e); }
  listPatients(t: string) { return PatientCrud(this.db).list(t); }
  deletePatient(t: string, id: EntityId) { return PatientCrud(this.db).delete(t, id); }
}

// ============================================================
// clinic-prescriptions
// ============================================================
const PrescriptionCrud = (db: DatabaseType) => makeCrud<Prescription>(db, {
  table: "clinic_prescriptions",
  columns: ["id", "tenant_id", "patient_id", "doctor_staff_id", "medical_record_id", "medication_name", "dosage", "duration_days", "refills_remaining", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    patientId: r.patient_id as string,
    doctorStaffId: r.doctor_staff_id as string,
    medicalRecordId: (r.medical_record_id as string | null) ?? null,
    medicationName: r.medication_name as string,
    dosage: r.dosage as string,
    durationDays: r.duration_days as number,
    refillsRemaining: r.refills_remaining as number,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    patient_id: e.patientId,
    doctor_staff_id: e.doctorStaffId,
    medical_record_id: e.medicalRecordId,
    medication_name: e.medicationName,
    dosage: e.dosage,
    duration_days: e.durationDays,
    refills_remaining: e.refillsRemaining,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteClinicPrescriptionsStore implements ClinicPrescriptionsStore {
  constructor(private readonly db: DatabaseType) {}
  getPrescription(t: string, id: EntityId) { return PrescriptionCrud(this.db).get(t, id); }
  putPrescription(t: string, e: Prescription) { PrescriptionCrud(this.db).put(t, e); }
  listPrescriptions(t: string) { return PrescriptionCrud(this.db).list(t); }
  deletePrescription(t: string, id: EntityId) { return PrescriptionCrud(this.db).delete(t, id); }
}

// ============================================================
// clinic-reminders
// ============================================================
const ReminderCrud = (db: DatabaseType) => makeCrud<Reminder>(db, {
  table: "clinic_reminders",
  columns: ["id", "tenant_id", "patient_id", "reminder_type", "scheduled_for", "payload_json", "status", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    patientId: r.patient_id as string,
    reminderType: r.reminder_type as string,
    scheduledFor: r.scheduled_for as string,
    payloadJson: r.payload_json as string,
    status: r.status as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    patient_id: e.patientId,
    reminder_type: e.reminderType,
    scheduled_for: e.scheduledFor,
    payload_json: e.payloadJson,
    status: e.status,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteClinicRemindersStore implements ClinicRemindersStore {
  constructor(private readonly db: DatabaseType) {}
  getReminder(t: string, id: EntityId) { return ReminderCrud(this.db).get(t, id); }
  putReminder(t: string, e: Reminder) { ReminderCrud(this.db).put(t, e); }
  listReminders(t: string) { return ReminderCrud(this.db).list(t); }
  deleteReminder(t: string, id: EntityId) { return ReminderCrud(this.db).delete(t, id); }
}

// ============================================================
// clinic-staff-management
// ============================================================
const StaffCrud = (db: DatabaseType) => makeCrud<Staff>(db, {
  table: "clinic_staffs",
  columns: ["id", "tenant_id", "first_name", "last_name", "role", "specialty", "phone", "email", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    firstName: r.first_name as string,
    lastName: r.last_name as string,
    role: r.role as string,
    specialty: (r.specialty as string | null) ?? null,
    phone: (r.phone as string | null) ?? null,
    email: (r.email as string | null) ?? null,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    first_name: e.firstName,
    last_name: e.lastName,
    role: e.role,
    specialty: e.specialty,
    phone: e.phone,
    email: e.email,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteClinicStaffManagementStore implements ClinicStaffManagementStore {
  constructor(private readonly db: DatabaseType) {}
  getStaff(t: string, id: EntityId) { return StaffCrud(this.db).get(t, id); }
  putStaff(t: string, e: Staff) { StaffCrud(this.db).put(t, e); }
  listStaffs(t: string) { return StaffCrud(this.db).list(t); }
  deleteStaff(t: string, id: EntityId) { return StaffCrud(this.db).delete(t, id); }
}

// ============================================================
// clinic-triage
// ============================================================
const Triage_entryCrud = (db: DatabaseType) => makeCrud<TriageEntry>(db, {
  table: "clinic_triage_entries",
  columns: ["id", "tenant_id", "patient_id", "visit_reason", "symptoms_json", "urgency", "classified_by_staff_id", "created_at", "updated_at"],
  fromRow: (r) => ({
    id: r.id as EntityId,
    tenantId: r.tenant_id as TenantId,
    patientId: r.patient_id as string,
    visitReason: r.visit_reason as string,
    symptomsJson: (r.symptoms_json as string | null) ?? null,
    urgency: r.urgency as string,
    classifiedByStaffId: r.classified_by_staff_id as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  }),
  toParams: (tenantId, e) => ({
    id: e.id, tenant_id: tenantId,
    patient_id: e.patientId,
    visit_reason: e.visitReason,
    symptoms_json: e.symptomsJson,
    urgency: e.urgency,
    classified_by_staff_id: e.classifiedByStaffId,
    created_at: e.createdAt, updated_at: e.updatedAt,
  }),
});

export class SqliteClinicTriageStore implements ClinicTriageStore {
  constructor(private readonly db: DatabaseType) {}
  getTriageEntry(t: string, id: EntityId) { return Triage_entryCrud(this.db).get(t, id); }
  putTriageEntry(t: string, e: TriageEntry) { Triage_entryCrud(this.db).put(t, e); }
  listTriageEntrys(t: string) { return Triage_entryCrud(this.db).list(t); }
  deleteTriageEntry(t: string, id: EntityId) { return Triage_entryCrud(this.db).delete(t, id); }
}
